apiVersion: bcc.bd-apaas.com/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressRoute.host }}`)
      services:
        - kind: Service
          name: "{{ .Release.Name }}-frontendproxy"
          port: 8080
  tls: {}
